services:
  - type: web
    name: botli-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn botly_api:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
